"""add flight_tickets

Revision ID: efc6f62e8f90
Revises: 7da965a5bbb8
Create Date: 2026-06-08 18:11:32.161675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc6f62e8f90'
down_revision: Union[str, None] = '7da965a5bbb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('airline', sa.String(length=200), nullable=False),
    sa.Column('flight_number', sa.String(length=50), nullable=True),
    sa.Column('pnr', sa.String(length=50), nullable=True),
    sa.Column('cabin_class', sa.String(length=50), nullable=True),
    sa.Column('origin', sa.String(length=150), nullable=True),
    sa.Column('destination', sa.String(length=150), nullable=True),
    sa.Column('depart_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrive_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('num_passengers', sa.Integer(), nullable=True),
    sa.Column('passengers', sa.JSON(), nullable=True),
    sa.Column('fare', sa.String(length=50), nullable=True),
    sa.Column('baggage', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_tickets_customer_id'), 'flight_tickets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_flight_tickets_id'), 'flight_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_flight_tickets_lead_id'), 'flight_tickets', ['lead_id'], unique=False)
    op.create_index(op.f('ix_flight_tickets_org_id'), 'flight_tickets', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_tickets_org_id'), table_name='flight_tickets')
    op.drop_index(op.f('ix_flight_tickets_lead_id'), table_name='flight_tickets')
    op.drop_index(op.f('ix_flight_tickets_id'), table_name='flight_tickets')
    op.drop_index(op.f('ix_flight_tickets_customer_id'), table_name='flight_tickets')
    op.drop_table('flight_tickets')
    # ### end Alembic commands ###
