"""add lead_partners

Revision ID: fbd848f261ad
Revises: efc6f62e8f90
Create Date: 2026-06-08 18:27:42.621510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd848f261ad'
down_revision: Union[str, None] = 'efc6f62e8f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('b2b_partner_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['b2b_partner_id'], ['b2b_partners.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_partners_b2b_partner_id'), 'lead_partners', ['b2b_partner_id'], unique=False)
    op.create_index(op.f('ix_lead_partners_id'), 'lead_partners', ['id'], unique=False)
    op.create_index(op.f('ix_lead_partners_lead_id'), 'lead_partners', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_partners_org_id'), 'lead_partners', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_partners_org_id'), table_name='lead_partners')
    op.drop_index(op.f('ix_lead_partners_lead_id'), table_name='lead_partners')
    op.drop_index(op.f('ix_lead_partners_id'), table_name='lead_partners')
    op.drop_index(op.f('ix_lead_partners_b2b_partner_id'), table_name='lead_partners')
    op.drop_table('lead_partners')
    # ### end Alembic commands ###
